name: Trivy Docker Security Scan

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  trivy-scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Install Trivy
        uses: aquasecurity/trivy-action@v0.31.0

      - name: Create report folder
        run: mkdir -p report

      - name: Trivy FS scan (before Docker build)
        uses: aquasecurity/trivy-action@v0.31.0
        with:
          scan-type: fs
          format: json
          output: report/trivy_fs_scan_$(date +%Y-%m-%d_%H-%M-%S).json

      - name: Build Docker image
        run: docker build -t flask_docker_app:latest .

      - name: Trivy Image scan (after Docker build)
        uses: aquasecurity/trivy-action@v0.31.0
        with:
          image-ref: flask_docker_app:latest
          format: json
          output: report/trivy_image_scan_$(date +%Y-%m-%d_%H-%M-%S).json

      - name: List generated reports
        run: ls -l report
